version: &docsyVersion 0.14.3
version_menu: *docsyVersion
versions:
  - name: Next
    kind: next
    url: https://main--docsydocs.netlify.app/
  - version: *docsyVersion
    kind: latest
    url: https://www.docsy.dev
