# cSpell:ignore pagelinks

tdVersion:
  latest: &tdLatestVers v0.14.3
  dev: &tdDevVers v0.14.4-dev
  buildId: &tdBuildId 023-over-main-3bcb7385

version: &tdDocRootedVers Doc-rooted of Next
version_menu: *tdLatestVers
version_menu_pagelinks: false
versions:
  - name: '**Versions**'
  - name: Next
    version: *tdDevVers
    # kind: next
    url: https://main--docsydocs.netlify.app
  - version: *tdLatestVers
    kind: latest
    url: https://www.docsy.dev
  - name: ---
  - name: '**Variant**'
  - name: Doc-rooted (experimental)
    version: *tdDocRootedVers
    kind: home
    pagelinks: false # TODO: drop this once /docs/* redirects are implemented
    url: https://doc-rooted--docsydocs.netlify.app
