# cSpell:ignore pagelinks

version: &docsyVersion 0.14.2
version_menu: *docsyVersion
versions:
  - name: Next
    kind: next
    url: https://main--docsydocs.netlify.app/
    pagelinks: false
  - version: *docsyVersion
    kind: latest
    url: https://www.docsy.dev
    pagelinks: false
