# cSpell:ignore pagelinks
#
# Version related parameters
#
# archived_version: false # TODO: generalize status
# version:
#   status: archived # Then fetch include

version: &docsyVersion 0.14.3-dev
tdBuildId: 013-over-main-38978ffc
versionLatest: &versionLatest v0.14.2
version_menu: *docsyVersion
version_menu_pagelinks: true
versions:
  # - name: '**About**'
  #   url: /project
  #   pagelinks: false
  # - name: ---
  - name: '**Versions**'
  - name: Next
    version: *docsyVersion
    # TODO: use https://next.docsy.dev once it's available
    url: https://main--docsydocs.netlify.app
  - version: *versionLatest
    url: https://www.docsy.dev
    kind: latest
  - name: ---
  - name: '**Variant**'
  - name: Doc-rooted
    url: https://doc-rooted--docsydocs.netlify.app
    # TODO: implement /docs/* redirects for doc-rooted site, then drop pagelinks:false
    pagelinks: false
    kind: home
  # - name: Goldydocs
  #   url: https://example.docsy.dev
  #   pagelinks: false
